# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cobrinha.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Snake(object):
    def setupUi(self, Snake):
        Snake.setObjectName("Snake")
        Snake.resize(733, 530)
        Snake.setStyleSheet("background-color:#55aa7f;")
        self.label = QtWidgets.QLabel(Snake)
        self.label.setGeometry(QtCore.QRect(190, 110, 331, 291))
        self.label.setAutoFillBackground(True)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("snake.jpg"))
        self.label.setScaledContents(True)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")

        self.retranslateUi(Snake)
        QtCore.QMetaObject.connectSlotsByName(Snake)

    def retranslateUi(self, Snake):
        _translate = QtCore.QCoreApplication.translate
        Snake.setWindowTitle(_translate("Snake", "Form"))
